language: node_js

install: echo "install"

script: npm run build

node_js:
  - "0.12"
  - "iojs"
  - "0.10"

notifications:
  irc:
    use_notice: true
    on_success: change
    on_failure: change
    channels:
      - chat.freenode.net#cf-abacus
